### ISSUE TITLE
Allow Buffer?

### ISSUE THREAD

**Issue by bezoerb** [sindresorhus/normalize-newline#2]
What about allowing Buffers as input?

**Comment by sindresorhus** [comment]
I would accept a good pull request with tests, but not something I personally need.

**Comment by bezoerb** [comment]
Thanks. That's fair enough :)
I'll make something ready as soon as i've some more time.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/strip-eof/blob/master/index.js for a similar thing that also supports buffer.

**Comment by sindresorhus** [comment]
Fixed by #3.
